- app/models/character.rb
- config/routes.rb
- db/migrate/20221114221320_create_characters.rb
- test/controllers/characters_controller_test.rb
- test/models/character_test.rb
> Generated character model

- Gemfile.lock
- app/models/booking.rb
- db/migrate/20221114221619_create_bookings.rb
- test/models/booking_test.rb
I added model booking migration. i need character model for run db:migrate. Cause two foreign key
> Add booking model

- app/views/shared/_navbar.html.erb
- db/schema.rb
- db/seeds.rb
see if you like the custom navbar
> Customize navbar

- app/models/character.rb
> added validation to character model

- app/models/booking.rb
need someone to review validations
> added validations for booking model

- db/seeds.rb
> confirmed seeds for user, booking, character

- app/assets/stylesheets/config/_colors.scss
$yellow: #f8fc1e; // element color
$light-gray: #e0e0e0; //back ground color
$black: #0d0c11; // font color
> add color panel

- app/controllers/bookings_controller.rb
- config/routes.rb
- test/controllers/bookings_controller_test.rb
> created bookings controller with some actions

- app/controllers/characters_controller.rb
- app/views/characters/my_characters.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
> my-characters method + view done

- app/assets/stylesheets/components/_cards.scss
- app/controllers/bookings_controller.rb
- app/controllers/characters_controller.rb
- app/views/bookings/my_bookings.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- app/views/characters/show.html.erb
- config/routes.rb
- db/migrate/20221115184250_set_default_status_to_0.rb
- db/schema.rb
I used card-trip for my-bookings page
> Added my-bookings to see all my bookings and bookings can be saved

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/models/user.rb
- app/views/bookings/my_bookings.html.erb
- app/views/bookings/show.html.erb
- config/routes.rb
- db/migrate/20221115204501_remove_default_from_bookings_table.rb
- db/schema.rb
> removed default from status; set enum for booking.rb

- app/controllers/characters_controller.rb
- app/views/characters/my_characters.html.erb
- app/views/characters/new.html.erb
- app/views/characters/show.html.erb
> add new character method created

- app/views/bookings/show.html.erb
> changed to nill and pending

- Gemfile
- Gemfile.lock
- app/controllers/characters_controller.rb
- app/views/characters/show.html.erb
- config/routes.rb
> Updated gemfile

- app/models/booking.rb
status default is nill and doesn't have validation
> removed status validation

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/characters_controller.rb
- app/models/character.rb
- app/views/characters/new.html.erb
- app/views/characters/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20221115214327_create_active_storage_tables.active_storage.rb
- db/schema.rb
added cloudinary gem. 
You might need to bundle for this.
> Add image upload for character

- app/views/characters/edit.html.erb
> added cloudinary key

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/views/bookings/edit.html.erb
- app/views/bookings/my_bookings.html.erb
- app/views/bookings/show.html.erb
- config/routes.rb
- db/migrate/20221116170441_add_default_to_status_in_bookings_table.rb
- db/schema.rb
> fixed the issues with the showpages, new action-edit created

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_cards.scss
- app/views/characters/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
> index done

- app/views/characters/show.html.erb
please review the minor change in show page
> fixed the characters showpage

- app/assets/stylesheets/pages/_home.scss
- app/views/bookings/host_bookings.html.erb
- app/views/bookings/my_bookings.html.erb
- app/views/shared/_navbar.html.erb
> card images and banner location

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/characters_controller.rb
- app/views/bookings/host_bookings.html.erb
- app/views/bookings/my_bookings.html.erb
- app/views/characters/index.html.erb
- app/views/characters/my_characters.html.erb
- app/views/characters/show.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
> containers in each pages instead of body

- app/controllers/characters_controller.rb
- app/javascript/controllers/map_controller.js
- app/views/characters/index.html.erb
- app/views/characters/show.html.erb
review please, map was added to show page with exact location
> map is now on the showpage with the pinned location of character

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/characters/index.html.erb
- app/views/characters/my_characters.html.erb
- app/views/characters/show.html.erb
> index cards done, show page needs more work

- app/views/characters/show.html.erb
> show page image half done, details need to be fixed

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/characters/show.html.erb
> Char show page

- app/views/bookings/edit.html.erb
- app/views/bookings/show.html.erb
> booking price

- app/views/bookings/edit.html.erb
- app/views/bookings/show.html.erb
> price fixed
